"""migration4

Revision ID: 7b7b74b0df7c
Revises: 98c975ec26f3
Create Date: 2025-05-03 18:50:15.676661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b7b74b0df7c'
down_revision: Union[str, None] = '98c975ec26f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('url', sa.String(length=255), nullable=False))
    op.drop_column('images', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('data', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('images', 'url')
    # ### end Alembic commands ###
