"""migration3

Revision ID: 98c975ec26f3
Revises: bf1b9b05944c
Create Date: 2025-05-03 16:39:09.823479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98c975ec26f3'
down_revision: Union[str, None] = 'bf1b9b05944c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('pass_point_id', sa.Integer(), nullable=False))
    op.drop_constraint('images_pereval_id_fkey', 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'pereval_added', ['pass_point_id'], ['id'])
    op.drop_column('images', 'pereval_id')
    op.add_column('pereval_added', sa.Column('beautyTitle', sa.String(length=20), nullable=False))
    op.drop_column('pereval_added', 'beauty_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pereval_added', sa.Column('beauty_title', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('pereval_added', 'beautyTitle')
    op.add_column('images', sa.Column('pereval_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key('images_pereval_id_fkey', 'images', 'pereval_added', ['pereval_id'], ['id'])
    op.drop_column('images', 'pass_point_id')
    # ### end Alembic commands ###
