"""migration

Revision ID: bdf14580f079
Revises: 3dd1b744bf71
Create Date: 2025-05-02 16:14:15.334724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdf14580f079'
down_revision: Union[str, None] = '3dd1b744bf71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('pass_point_id', sa.Integer(), nullable=False))
    op.add_column('images', sa.Column('data', sa.String(), nullable=False))
    op.drop_constraint('images_pass_id_fkey', 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'pereval_added', ['pass_point_id'], ['id'])
    op.drop_column('images', 'pass_id')
    op.add_column('pereval_added', sa.Column('beauty_title', sa.String(length=20), nullable=False))
    op.drop_column('pereval_added', 'beautyTitle')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pereval_added', sa.Column('beautyTitle', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('pereval_added', 'beauty_title')
    op.add_column('images', sa.Column('pass_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key('images_pass_id_fkey', 'images', 'pereval_added', ['pass_id'], ['id'])
    op.drop_column('images', 'data')
    op.drop_column('images', 'pass_point_id')
    # ### end Alembic commands ###
