"""migration2

Revision ID: bf1b9b05944c
Revises: bdf14580f079
Create Date: 2025-05-02 16:19:52.381077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf1b9b05944c'
down_revision: Union[str, None] = 'bdf14580f079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('pereval_id', sa.Integer(), nullable=False))
    op.drop_constraint('images_pass_point_id_fkey', 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'pereval_added', ['pereval_id'], ['id'])
    op.drop_column('images', 'pass_point_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('pass_point_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key('images_pass_point_id_fkey', 'images', 'pereval_added', ['pass_point_id'], ['id'])
    op.drop_column('images', 'pereval_id')
    # ### end Alembic commands ###
