"""migration4

Revision ID: f1b8945977ce
Revises: fcfbe0b5cbf5
Create Date: 2025-05-09 20:06:18.575987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1b8945977ce'
down_revision: Union[str, None] = 'fcfbe0b5cbf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('data', sa.String(length=255), nullable=False))
    op.drop_column('images', 'url')
    op.add_column('pereval_added', sa.Column('beauty_title', sa.String(length=20), nullable=False))
    op.alter_column('pereval_added', 'add_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.drop_column('pereval_added', 'beautyTitle')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pereval_added', sa.Column('beautyTitle', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.alter_column('pereval_added', 'add_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('pereval_added', 'beauty_title')
    op.add_column('images', sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('images', 'data')
    # ### end Alembic commands ###
