"""migration2

Revision ID: fcfbe0b5cbf5
Revises: 46ef348172fb
Create Date: 2025-05-09 19:31:10.632966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcfbe0b5cbf5'
down_revision: Union[str, None] = '46ef348172fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pereval_added', 'add_time',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pereval_added', 'add_time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
